config/routes.rb
Rails.application.routes.draw do
  resources :news_categories
  resources :authors
  resources :gallery_images
  resources :videos
  resources :news
  resources :galleries
  resources :events
  resources :banners

  resources :front_galleries, path: 'fotos'
  resources :front_events, path: 'agenda'
  resources :front_videos, path: 'videos-web'
  resources :front_news, path: 'colunas'
  resources :front_companies, path: 'guia-empresarial'

  match "colunas/por-colunista/:author_id", :to => "front_news#by_author", :as => :news_by_author, via: :get

  get 'fale-conosco' => 'front_talk_with_us#index', as: :front_talk_with_us
  post 'fale-conosco/enviar' => 'front_talk_with_us#deliver', as: :send_contact

  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/banner.rb
class Banner < ActiveRecord::Base

  has_attached_file :image, styles: {slider: '470x409#', top: '210x409#',
    top_small: '295x131#', header: '602x68#'}, default_style: :slider,
    convert_options: {slider: "-quality 90 -strip", top: "-quality 90 -strip",
      top_small: "-quality 90 -strip", header: "-quality 90 -strip"}
  do_not_validate_attachment_file_type :image

  def self.active
    where(active: true)
  end

  def self.sorted
    order(created_at: :desc)
  end
end

app/controllers/banners_controller.rb
class BannersController < AdminController
  before_action :set_banner, only: [:show, :edit, :update, :destroy]

  # GET /banners
  # GET /banners.json
  def index
    @banners = Banner.all
  end

  # GET /banners/1
  # GET /banners/1.json
  def show
  end

  # GET /banners/new
  def new
    @banner = Banner.new
  end

  # GET /banners/1/edit
  def edit
  end

  # POST /banners
  # POST /banners.json
  def create
    @banner = Banner.new(banner_params)

    respond_to do |format|
      if @banner.save
        format.html { redirect_to banners_url, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :created, location: @banner }
      else
        format.html { render :new }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banners/1
  # PATCH/PUT /banners/1.json
  def update
    respond_to do |format|
      if @banner.update(banner_params)
        format.html { redirect_to banners_url, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :ok, location: @banner }
      else
        format.html { render :edit }
        format.json { render json: @banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /banners/1
  # DELETE /banners/1.json
  def destroy
    @banner.destroy
    respond_to do |format|
      format.html { redirect_to banners_url, notice: 'Registro apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banner
      @banner = Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def banner_params
      params.require(:banner).permit(:title, :image, :url, :slider, :top,
        :top_small, :header, :active)
    end
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/views/banners/_form.html.erb
<%= form_for(@banner) do |f| %>
  <% if @banner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@banner.errors.count, "erros") %> encontrados:</h2>

      <ul>
      <% @banner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :slider %><br>
    <%= f.check_box :slider %>
  </div>
  <div class="field">
    <%= f.label :top %><br>
    <%= f.check_box :top %>
  </div>
  <div class="field">
    <%= f.label :top_small %><br>
    <%= f.check_box :top_small %>
  </div>
  <div class="field">
    <%= f.label :header %><br>
    <%= f.check_box :header %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/banners/edit.html.erb
<h1>Editing banner</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @banner %> |
<%= link_to 'Voltar', banners_path %>

app/views/banners/index.html.erb
<h1><%= admin_title('Lista de banners') %></h1>

<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>URL</th>
      <th>Slider?</th>
      <th>Top direito?</th>
      <th>Pequeno?</th>
      <th>Superior?</th>
      <th>Ativo?</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @banners.each do |banner| %>
      <tr>
        <td><%= banner.title %></td>
        <td><%= banner.url %></td>
        <td><%= banner.slider ? 'Sim' : 'Não' %></td>
        <td><%= banner.top ? 'Sim' : 'Não' %></td>
        <td><%= banner.top_small ? 'Sim' : 'Não' %></td>
        <td><%= banner.header ? 'Sim' : 'Não' %></td>
        <td><%= banner.active ? 'Sim' : 'Não' %></td>
        <td><%= link_to 'Editar', edit_banner_path(banner) %></td>
        <td><%= link_to 'Apagar', banner, method: :delete, data: { confirm: 'Tem certeza disto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Banner', new_banner_path %>

app/views/banners/new.html.erb
<h1><%=admin_title('Novo banner')%></h1>

<%= render 'form' %>

<%= link_to 'Voltar', banners_path %>

app/views/banners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @banner.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @banner.image %>
</p>

<p>
  <strong>Url:</strong>
  <%= @banner.url %>
</p>

<p>
  <strong>Slider:</strong>
  <%= @banner.slider %>
</p>

<p>
  <strong>Top:</strong>
  <%= @banner.top %>
</p>

<p>
  <strong>Top small:</strong>
  <%= @banner.top_small %>
</p>

<p>
  <strong>Active:</strong>
  <%= @banner.active %>
</p>

<%= link_to 'Editar', edit_banner_path(@banner) %> |
<%= link_to 'Voltar', banners_path %>