config/routes.rb
Rails.application.routes.draw do
  resources :news_categories
  resources :authors
  resources :gallery_images
  resources :videos
  resources :news
  resources :galleries
  resources :events
  resources :banners

  resources :front_galleries, path: 'fotos'
  resources :front_events, path: 'agenda'
  resources :front_videos, path: 'videos-web'
  resources :front_news, path: 'colunas'
  resources :front_companies, path: 'guia-empresarial'

  match "colunas/por-colunista/:author_id", :to => "front_news#by_author", :as => :news_by_author, via: :get

  get 'fale-conosco' => 'front_talk_with_us#index', as: :front_talk_with_us
  post 'fale-conosco/enviar' => 'front_talk_with_us#deliver', as: :send_contact

  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, :singer, :youtube_code, presence: true

  def self.active
    where(active: true)
  end

  def self.sorted
    order(created_at: :desc)
  end
end

app/controllers/videos_controller.rb
class VideosController < AdminController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_url, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to videos_url, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Registro apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :singer, :youtube_code, :active)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@video.errors.count, "erros") %> encontrados:</h4>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :singer %><br>
    <%= f.text_field :singer %>
  </div>
  <div class="field">
    <%= f.label :youtube_code %><br>
    <%= f.text_field :youtube_code %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1><%= admin_title('Editando Vídeo') %></h1>

<%= render 'form' %>

<%= link_to 'Voltar', videos_path %>

app/views/videos/index.html.erb
<h1><%= admin_title('Lista de Vídeos') %></h1>

<table>
  <thead>
    <tr>
      <th>Título</th>
      <th>Cantor</th>
      <th>Código Youtube</th>
      <th>Active?</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.singer %></td>
        <td><%= video.youtube_code %></td>
        <td><%= video.active ? 'Sim' : 'Não' %></td>
        <td><%= link_to 'Editar', edit_video_path(video) %></td>
        <td><%= link_to 'Apagar', video, method: :delete, data: { confirm: 'Tem certeza disto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Video', new_video_path %>

app/views/videos/new.html.erb
<h1><%= admin_title('Novo Vídeo') %></h1>

<%= render 'form' %>

<%= link_to 'Voltar', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Singer:</strong>
  <%= @video.singer %>
</p>

<p>
  <strong>Youtube url:</strong>
  <%= @video.youtube_code %>
</p>

<p>
  <strong>Active:</strong>
  <%= @video.active %>
</p>

<%= link_to 'Editar', edit_video_path(@video) %> |
<%= link_to 'Voltar', videos_path %>