config/routes.rb
Rails.application.routes.draw do
  resources :news_categories
  resources :authors
  resources :gallery_images
  resources :videos
  resources :news
  resources :galleries
  resources :events
  resources :banners

  resources :front_galleries, path: 'fotos'
  resources :front_events, path: 'agenda'
  resources :front_videos, path: 'videos-web'
  resources :front_news, path: 'colunas'
  resources :front_companies, path: 'guia-empresarial'

  match "colunas/por-colunista/:author_id", :to => "front_news#by_author", :as => :news_by_author, via: :get

  get 'fale-conosco' => 'front_talk_with_us#index', as: :front_talk_with_us
  post 'fale-conosco/enviar' => 'front_talk_with_us#deliver', as: :send_contact

  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @slider_banners = Banner.active.where(slider: true).sorted
    @top_banner = Banner.active.where(top: true).first
    @top_small_banners = Banner.active.where(top_small: true).sorted

    @last_news = News.active.limit(8).sorted

    @last_galleries = Gallery.active.limit(4).sorted
    @top_galleries = Gallery.active.limit(8).order(views: :asc, occur_at: :desc)

    @next_event = Event.active.sorted.first
    @top_events = Event.active.limit(8).order(views: :asc, occur_at: :desc)

    @last_videos = Video.active.limit(6).sorted

    @last_companies = Company.active.limit(4).order(created_at: :desc)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% unless @slider_banners.blank? %>
<script type="text/javascript">
  jQuery(document).on("page:load ready", function(){
    $('.slider')._TMS({
      preset:'zoomer',
      show:0,
      pauseOnHover:'false',
      duration:10000,
      pagination:$('.img-pags').uCarousel({show:4,shift:0}),
      slideshow:700,
      numStatus:false,
      banners:false,
      waitBannerAnimation:false
    });
    jQuery(".latestpost .play-pause .play").append("<span>Play</span>");
    jQuery(".latestpost .play-pause .pause").append("<span>Pause</span>");
    jQuery(".latestpost .play-pause .loading").append("<span>Load...</span>");
    jQuery(".latestpost .play-pause .error").append("<span>Error!</span>");
  });
</script>
<% content_for(:slider) do %>
<section id="slider-wrapper">
  <div id="slider">
    <div class="slider">
      <ul class="items">
        <%= @slider_banners.each_with_index do |banner,i| %>
        <li>
          <a href='<%= banner.url %>'><img src='<%= banner.image.url(:slider) %>' alt='<%= banner.title %>' title='#sliderCaption<%=i + 1%>' /></a>
        </li>
        <% end -%>
      </ul>
    </div>
    <div class="pag">
      <div class="img-pags">
        <ul>
          <% @slider_banners.each_with_index do |banner,i| %>
          <li>
            <a href='<%= banner.url %>'><img src='<%= banner.image.url(:slider) %>' alt='<%= banner.title %>' title='#sliderCaption<%=i + 1%>' /></a><em><a class='title' href='<%= banner.url %>'><%= banner.title %></a></em><time datetime='<%= l banner.created_at %>'><%= l banner.created_at %></time>
          </li>
          <% end -%>
        </ul>
      </div>
      <% if @slider_banners.count > 4 %>
      <div class="pags-bg">
        <a href="#" class="btn button1" data-type="prevPage"></a>
        <a href="#" class="btn button2" data-type="nextPage"></a>
      </div>
      <% end -%>
    </div>
  </div>
  <% if @top_banner %>
  <div id="banner-area">
    <div id="my_tweetbanner-2">
      <a href="<%= @top_banner.url %>" class="bnr"><img src="<%= @top_banner.image.url(:top) %>" alt="" /></a>
    </div>
  </div><!--#widget-header-->
  <% end -%>
  <div class="clear"></div>
</section><!--#slider-->
<% end -%>
<% end -%>



<% unless @top_small_banners.blank? %>
<div class="grid_24">
  <div id="my_bannerswidget-4">
    <ul class="banners-holder clearfix">
      <% @top_small_banners.each do |banner| %>
      <li><a href="<%= banner.url %>" class="bnr"><img src="<%= banner.image.url(:top_small) %>" alt="<%= banner.title %>" /></a></li>
      <% end -%>
    </ul>
  </div>
</div>
<% end -%>
<div class="indent-bot">
  <div class="grid_6 top-star-news maxheight">
    <div id="my_postwidget-3">
      <div class='title-box'>
        <h3>Últimas Fotos</h3>
        <!-- Link under post cycle -->
        <a href="<%= front_galleries_path %>" class="link">ver todas</a>
      </div>

      <ul class="latestpost">

        <% @last_galleries.each do |gallery| %>
        <li class="clearfix">
          <!--audio -->
          <figure class="featured-thumbnail">
            <a href="<%= front_gallery_path(gallery) %>" title="<%=gallery.title%>"><img src="<%= gallery.image.url(:thumb)%>" alt="<%= gallery.title %>" /></a>
          </figure>
          <time datetime="<%= l(gallery.occur_at) %>"><%= l(gallery.occur_at) %></time>
          <h5><a href="<%= front_gallery_path(gallery) %>" rel="bookmark" title="<%=gallery.title%>"><%=gallery.title%></a></h5>
        </li>
        <% end -%>
      </ul>


    </div>
  </div>
  <div class="grid_6 hot-interview maxheight">
    <div id="my_poststypewidget-3">
      <div class='title-box'>
      <h3>Próximo Evento</h3>
        <a href="<%= front_events_path %>" class="link">Ver todos</a>
      </div>
      <% if @next_event %>
      <ul class='post_list hot_interview'>
        <li class="cat_post_item-1 clearfix">
          <div class="post_meta"><time datetime="<%= l @next_event.occur_at %>"><%= l @next_event.occur_at %></time></div>
          <a class="post-title" href="<%= front_event_path(@next_event) %>" rel="bookmark" title="<%= @next_event.title %>"><%= @next_event.title %></a>
          <div></div>
          <figure>
            <a href="<%= front_event_path(@next_event) %>">
              <img src="<%= @next_event.image.url(:next) %>" alt="<%= @next_event.title %>" />
            </a>
          </figure>
          <div class="post_content">
            <%= @next_event.description.html_safe %>
          </div>
          <a href="<%= front_event_path(@next_event) %>" class="button"><span>Mais detalhes</span></a>
        </li>
      </ul>
      <% end -%>

    </div>
  </div>
  <div class="grid_12 latest-new maxheight">
    <div id="my_carouselwidget-2">
      <div class='title-box'>
        <h3>Últimas postagens</h3>
      </div>
      <!-- Elastislide Carousel -->
      <div id="carousel">
        <div class="viewport">
          <ul class="overview">
            <% @last_news.each do |news| %>
            <li>
              <figure class="thumbnail"><a href="<%= front_news_path(news) %>"><img src="<%= news.image.url(:thumb) %>" alt="<%= news.title %>" /></a></figure>
              <div class="extra-wrap">
                <time datetime="<%= l news.occur_at %>"><%= l news.occur_at %></time>
                <div class="excerpt"><a href="<%= front_news_path(news) %>"><%= news.title %></a></div>
              </div>
            </li>
            <% end -%>

          </ul>
        </div>
        <a href="#" class="buttons next">next</a>
        <a href="#" class="buttons prev">prev</a>
      </div>
      <script type="text/javascript">
        jQuery(document).on("page:load ready", function(){
          jQuery('#carousel').tinycarousel({
                    start: 1, // where should the carousel start?
                    display: 1, // how many blocks do you want to move at 1 time?
                    axis: 'y', // vertical or horizontal scroller? ( x || y ).
                    controls: true, // show left and right navigation buttons.
                    pager: false, // is there a page number navigation present?
                    interval: false, // move to another block on intervals.
                    intervaltime: 5000, // interval time in milliseconds.
                    rewind: false, // If interval is true and rewind is true it will play in reverse if the last slide is reached.
                    animation: true, // false is instant, true is animate.
                    duration: 500, // how fast must the animation move in ms?
                    callback: null // function that executes after every move.
                  });
        });
      </script>
      <!-- End Elastislide Carousel -->


    </div>
  </div>
  <div class="clear"></div>
</div>
<div class="clearfix">
  <div class="grid_12">
    <div id="text-2">
      <div class="textwidget">
        <div class="tabs">
          <div class="tab-menu">
            <ul>
              <li><a href="#tab1">Fotos mais clicadas</a></li>
              <li><a href="#tab2">Eventos mais clicados</a></li>
            </ul>
            <div class="clear"></div>
          </div>
          <div class="tab-wrapper">
            <div id="tab1" class="tab">
              <ul class="popular_posts">
                <% @top_galleries.each do |gallery| %>
                <li><figure class="featured-thumbnail"><a href="<%= front_gallery_path(gallery) %>" title="<%= gallery.title %>"><img  src="<%= gallery.image.url(:thumb_top) %>"/><i></i></a></figure><a class="title" href="<%= front_gallery_path(gallery) %>" title="<%= gallery.title %>"><%= gallery.title %></a><div class="excerpt"><a href="<%= front_gallery_path(gallery) %>" title="Donec tempor libero"></a></div></li>
                <% end -%>
              </ul>
            </div>
            <div id="tab2" class="tab">
              <ul class="recent-posts ">
                <% @top_events.each do |event| %>
                <li class="post type-post format-standard hentry category-featured category-latest-news"><figure class="featured-thumbnail"><a href="<%= front_event_path(event) %>" title="<%= event.title %>"><img  src="<%= event.image.url(:thumb_top) %>"/><i></i></a></figure><h5><a class="title" href="<%= front_event_path(event) %>" title="<%= event.title %>"><%= event.title %></a></h5><div class="clear"></div></li>
                <% end -%>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="my_cyclewidget-3">
      <div class="title-box"><h3>Guia Empresarial</h3></div>
      <% if @last_companies.count > 1 %>
      <script type="text/javascript">
        jQuery(document).on("page:load ready", function(){
          jQuery('#post-cycle').cycle({
            pause: 1,
            fx: 'scrollHorz',
            cleartypeNoBg:true,
            manualTrump:false,
            timeout:0,
            prev:    '#prev-post',
            next:    '#next-post'
          });
        });
      </script>
      <% end -%>
      <div class="cycle_inner">
        <div class="post_cycle" id="post-cycle">
          <% @last_companies.each do |company| %>
          <div class="cycle_item">
            <figure class="featured-thumbnail">
              <a href="<%= front_company_path(company) %>" title="<%= company.name %>"><img src="<%= company.logo.url(:big) %>" style="width:190px" alt="<%= company.name %>" /><i></i></a>
            </figure>
            <time datetime="<%= l company.created_at %>"><%= company.company_categories.pluck(:name).to_sentence %></time>
            <h3><a href="<%= front_company_path(company) %>"><%= company.name %></a></h3>
          </div>
          <% end -%>
        </div>

        <div id="post-controls">
          <a id="next-post" href="#">next</a>
          <a id="prev-post" href="#">prev</a>
        </div>
      </div>
    </div>
  </div>
  <div class="grid_6 top-sound-box">
    <div id="my_postwidget-4">
      <div class='title-box'>
        <h3>Últimos Vídeos</h3>
        <!-- Link under post cycle -->
        <a href="<%= front_videos_path %>" class="link">Ver todos</a>
      </div>
      <ul class="latestpost">

        <% @last_videos.each_with_index do |video, i| %>
        <li class="clearfix">
          <!--audio -->
          <strong class="count">0<%= i+1 %></strong>
          <div class="extra-wrap">
            <h5><a href="http://www.youtube.com/watch?v=<%= video.youtube_code %>" target="_blank" title="<%= video.title %>"><%= video.title %></a></h5>
            <div class="excerpt"><%= video.singer %></div>
            <div class="audio-wrapper">
              <a class="audio-download" href="http://www.youtube.com/watch?v=<%= video.youtube_code %>" target="_blank">Ver vídeo</a>
            </div>
          </div>
          <!--video -->
        </li>
        <% end -%>
      </ul>


    </div>
  </div>
  <div class="grid_6 clips">
    <div id="my_postwidget-5">
      <div class='title-box'>
        <h3>Vídeos em destaque</h3>
      </div>

      <ul class="latestpost">
        <% @last_videos.all[0..1].each do |video| %>
        <li class="clearfix">
          <!--audio -->
          <iframe width="560" height="400" src="http://www.youtube.com/embed/<%=video.youtube_code%>" frameborder="0" allowfullscreen></iframe>
          <h5><a href="http://www.youtube.com/watch?v=<%= video.youtube_code %>" target="_blank" rel="bookmark" title="<%= video.title %>"><%= video.title %></a></h5>
          <!-- others -->
        </li>
        <% end -%>
      </ul>

    </div>
  </div>
</div>