config/routes.rb
Rails.application.routes.draw do
  resources :news_categories
  resources :authors
  resources :gallery_images
  resources :videos
  resources :news
  resources :galleries
  resources :events
  resources :banners

  resources :front_galleries, path: 'fotos'
  resources :front_events, path: 'agenda'
  resources :front_videos, path: 'videos-web'
  resources :front_news, path: 'colunas'
  resources :front_companies, path: 'guia-empresarial'

  match "colunas/por-colunista/:author_id", :to => "front_news#by_author", :as => :news_by_author, via: :get

  get 'fale-conosco' => 'front_talk_with_us#index', as: :front_talk_with_us
  post 'fale-conosco/enviar' => 'front_talk_with_us#deliver', as: :send_contact

  devise_for :users
  get 'home/index'

  root 'home#index'

end

app/models/news_category.rb
class NewsCategory < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates :name, presence: true

  def self.sorted
    order(name: :desc)
  end
end

app/controllers/news_categories_controller.rb
class NewsCategoriesController < AdminController
  before_action :set_news_category, only: [:show, :edit, :update, :destroy]

  # GET /news_categories
  # GET /news_categories.json
  def index
    @news_categories = NewsCategory.all
  end

  # GET /news_categories/1
  # GET /news_categories/1.json
  def show
  end

  # GET /news_categories/new
  def new
    @news_category = NewsCategory.new
  end

  # GET /news_categories/1/edit
  def edit
  end

  # POST /news_categories
  # POST /news_categories.json
  def create
    @news_category = NewsCategory.new(news_category_params)

    respond_to do |format|
      if @news_category.save
        format.html { redirect_to news_categories_url, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :created, location: @news_category }
      else
        format.html { render :new }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news_categories/1
  # PATCH/PUT /news_categories/1.json
  def update
    respond_to do |format|
      if @news_category.update(news_category_params)
        format.html { redirect_to news_categories_url, notice: 'Operação realizada com sucesso.' }
        format.json { render :show, status: :ok, location: @news_category }
      else
        format.html { render :edit }
        format.json { render json: @news_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_categories/1
  # DELETE /news_categories/1.json
  def destroy
    @news_category.destroy
    respond_to do |format|
      format.html { redirect_to news_categories_url, notice: 'Registro apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news_category
      @news_category = NewsCategory.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_category_params
      params.require(:news_category).permit(:name)
    end
end

app/helpers/news_categories_helper.rb
module NewsCategoriesHelper
end

app/views/news_categories/_form.html.erb
<%= form_for(@news_category) do |f| %>
  <% if @news_category.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@news_category.errors.count, "erros") %> encontrados:</h4>

      <ul>
      <% @news_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_categories/edit.html.erb
<h1><%= admin_title('Editando Coluna') %></h1>

<%= render 'form' %>

<%= link_to 'Voltar', news_categories_path %>

app/views/news_categories/index.html.erb
<h1><%= admin_title('Lista de Colunas') %></h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_categories.each do |news_category| %>
      <tr>
        <td><%= news_category.name %></td>
        <td><%= link_to 'Editar', edit_news_category_path(news_category) %></td>
        <td><%= link_to 'Apagar', news_category, method: :delete, data: { confirm: 'Tem certeza disto?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar coluna', new_news_category_path %>

app/views/news_categories/new.html.erb
<h1><%= admin_title('Nova Coluna') %></h1>

<%= render 'form' %>

<%= link_to 'Voltar', news_categories_path %>

app/views/news_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news_category.name %>
</p>

<%= link_to 'Edit', edit_news_category_path(@news_category) %> |
<%= link_to 'Back', news_categories_path %>